### PR TITLE
fix: console.error doesn't have to be a string in act.compat.js

### PR DESCRIPTION
**Pull request by rvdkooy**
What:
This PR fixes issue: #442 by adding type checking for args used in asyncAct function.

Why:
Current implementation assumes console.erorr was always called with a string even though it could be called with other types.

How:
Wrapped execution of code in a type check if statement to ensure operations are done only on string types.

Checklist:

- [ ]  Documentation added to the docs site N/A
- [x] Tests
- [ ] Typescript definitions updated N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
I'm happy to merge either of these once they pass the build and all the current tests :)

**Comment by rvdkooy** [comment]
actually found out that the `noop` scenario was never tested 
the previous 100% coverage was not really 100%

Added a test for this, coverage should be 100% again

**Comment by kentcdodds** [comment]
@all-contributors please add @rvdkooy for code and tests

**Pull request merged**
