### PR TITLE
fix: Update types to support all possible react component return values

### PR DESCRIPTION
**Pull request by trappar**
**What**: Fixes: https://github.com/testing-library/react-testing-library/issues/1271

**Why**: To improve typescript types

**How**: N/A

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs) N/A
- [x] Tests
- [x] TypeScript definitions updated
- [ ] Ready to be merged

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Thanks!

**Comment by eps1lon** [comment]
@all-contributors add @trappar  for code

**Comment by stephannielsen** [comment]
We see failures with this message now:

`Type '({ children }: { children: JSX.Element; }) => JSX.Element' is not assignable to type 'JSXElementConstructor<{ children: ReactNode; }> | undefined'.`

**Comment by asso1985** [comment]
Missing breaking change? Broke our tests.

**Pull request merged**
