### PR TITLE
test: Build in CodeSandbox CI

### PR DESCRIPTION
**Pull request by eps1lon**
**What**:

Build package in PRs for codesandbox

Closes #533

**Why**:

Integration testing, shareable live playground of new features etc

**How**:

https://twitter.com/codesandbox/status/1181184975460282368

**Checklist**:
- ~[ ] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs)~
- ~[ ] Tests~
- ~[ ] Typescript definitions updated~
- [x] Ready to be merged

### CODE REVIEW

**Comment by eps1lon** [comment]
Repository has to be whitelisted first (I guess because you can't have private apps on GitHub). I DMed Ives.

**Comment by MichaelDeBoey** [comment]
CodeSandbox CI is public now 🙂

https://codesandbox.io/post/codesandbox-ci-embeds

**Comment by eps1lon** [comment]
Huh, weird. @kentcdodds Could you check/reset the permissions again before I message Ives?

**Comment by kentcdodds** [comment]
Permissions are good 👍

**Comment by lbogdan** [comment]
Hey! We're now white-listing all newly added repositories, but we somehow omitted to also white-list the ones added before the official release. 🙂 I just did it now, and replayed the GitHub webhook, which triggered the build.

**Comment by kentcdodds** [comment]
Super! Is this ready to go @eps1lon?

**Comment by eps1lon** [comment]
> Super! Is this ready to go @eps1lon?

Oh right. Forget to mark as ready to merge. This is good to go.

**Pull request merged**
