### PR TITLE
feat(pure): add renderOptions support to render

### PR DESCRIPTION
**Pull request by naorpeled**
**What**:

**Why**:

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [x] TypeScript definitions updated
- [ ] Ready to be merged
      

closes 1297

### CODE REVIEW

**Comment by eps1lon** [comment]
We should flatten this instead of allowing arbitrary options. We don't know if a passing all through will make sense. If people want to access the root options directly, they can always switch to `createRoot` directly.

**Comment by naorpeled** [comment]
> We should flatten this instead of allowing arbitrary options. We don't know if a passing all through will make sense. If people want to access the root options directly, they can always switch to `createRoot` directly.

how should we handle the cases where the consumer uses the non-canary version that currently does not expose those options?

**Comment by eps1lon** [comment]
> how should we handle the cases where the consumer uses the non-canary version that currently does not expose those options?

Is there something different in that regard between your initial version and the version I proposed?

**Comment by naorpeled** [comment]
> > how should we handle the cases where the consumer uses the non-canary version that currently does not expose those options?
> 
> Is there something different in that regard between your initial version and the version I proposed?

It's different in the sense that we base the type definitions on what the version the consumer uses,
in React 18 they won't get type autocompletions for v19 canary definitions, and vice verse.

**Comment by eps1lon** [comment]
> Afaik it's different in the sense that we base the type definitions on what the version the consumer uses,
in React 18 they won't get type autocompletions for v19 canary definitions, and vice verse.

That's intended though, no? I don't see how type concerns need to dictate our API. It seems to me we can make flat options work. It just requires a bit more type-implementation work on our part.

**Comment by eps1lon** [comment]
Alternate: https://github.com/testing-library/react-testing-library/pull/1354

**Comment by naorpeled** [comment]
> Alternate: https://github.com/testing-library/react-testing-library/pull/1354

Sorry I ended up not finishing this task, had some IRL things to deal with.

Thanks for taking this task.

**Pull request closed without merging**
