### PR TITLE
fix: Specify a non-* version for @types/react-dom

### PR DESCRIPTION
**Pull request by Nokel81**
**What**: fixes https://github.com/testing-library/react-testing-library/issues/1039

**Why**: Updating to react@18 (including types) is broken when using `yarn` because it picks the wrong version

**How**: Testing

**Checklist**:

- [ ] N/A - Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] N/A - Tests
- [ ] N/A - TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
We probably want to switch to `peerDependencies` (see https://github.com/facebook/react/issues/24304#issuecomment-1094565891) but this is a step in the right direction. Thanks!

**Comment by Nokel81** [comment]
Thanks, in the meantime I did the nuclear option...

The CI errors seem to imply that there should be some things that need fixing, shall I update the PR to do that too?

**Comment by eps1lon** [comment]
@all-contributors add @Nokel81 for bug and code

**Comment by simkessy** [comment]
This is broken, resulting in: 

```

    Cannot find module 'react-dom/client' from '../../../node_modules/@testing-library/react/dist/pure.js'

    Require stack:
      /home/node_modules/@testing-library/react/dist/pure.js
      /home/node_modules/@testing-library/react/dist/index.js
      src/components/review_details/Formatters/LinkFormatter.test.jsx
```

**Pull request merged**
