### PR TITLE
chore: rename master to main in all references

### PR DESCRIPTION
**Pull request by MatanBobi**
**What**: Prepare to migrate master branch to main

**Why**: 

**How**:

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [ ] Tests
- [ ] Typescript definitions updated
- [ ] Ready to be merged
      

After that, we will need to rename the branch manually I guess..
I might be missing something because I'm not too familiar with how to do it so I just did it manually.
If there's an automatic process I don't know, please let me know :)

### CODE REVIEW

**Review by eps1lon — APPROVED** [review]
Looks good. Will wait a bit to give others a chance to review.

**Review by marcosvega91 — APPROVED** [review]
It looks good :)

**Review by nickmccurdy — APPROVED** [review]
This is good, but we'll also want to rename the branch on GitHub (relatively new feature) when it's merged.

**Comment by eps1lon** [comment]
> This is good, but we'll also want to rename the branch on GitHub (relatively new feature) when it's merged.

Renamed before merge to see if this PR works as intended once merged.

**Pull request merged**
