### PR TITLE
fix: Trigger onPointerEnter/Leave when calling pointerEnter/Leave

### PR DESCRIPTION
**Pull request by karthick3018**
**Pointer events added**:

**Existing code doesn't include pointer events**:

**Similar to the mouse events**:

**Checklist**:

- [ ] Documentation added to the N/A
      [docs site](https://github.com/testing-library/testing-library-docs)
- [x] Tests
- [ ] Typescript definitions updated  N/A
- [x] Ready to be merged

### CODE REVIEW

**Comment by kentcdodds** [comment]
Thanks for this! Could we get some tests please?

**Comment by karthick3018** [comment]
> Thanks for this! Could we get some tests please?

hey @kentcdodds  added a passing test case

**Review by kentcdodds — APPROVED** [review]
LGTM. What do you think @eps1lon?

**Comment by eps1lon** [comment]
@all-contributors add @karthick3018 for code

**Pull request merged**
