### PR TITLE
docs: use "msw" for API mocking in examples

### PR DESCRIPTION
**Pull request by kettanaito**
**What**:

Uses `msw` library for API mocking in the test suite example in README.

**Why**:

These changes are implemented similar to the [React Example](https://testing-library.com/docs/react-testing-library/example-intro) from the Testing Library documentation. 

**How**:

- Initial request handler via `setupServer`
- Per-test setup handler via `server.use()`, allowing to test an error scenario

**Checklist**:

- [x] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs)
- [x] Tests (not applicable)
- [x] Typescript definitions updated (not applicable)
- [x] Ready to be merged
      

- Follow up to https://github.com/testing-library/testing-library-docs/issues/482

### CODE REVIEW

**Comment by kettanaito** [comment]
I've also split the two code blocks, assuming there's been a typo and they were merged together by mistake (they showcase two different files). Please let me know if that was intentional, I'll revert the change. Thanks!

**Comment by kentcdodds** [comment]
@all-contributors please add @kettanaito for docs

**Comment by kettanaito** [comment]
@kentcdodds, thanks for the review! Honored to be a part of this!

**Pull request merged**
