### PR TITLE
fix(cleanup-after-each): remove cleanup-after-each file.

### LINKED ISSUE #432: Remove cleanup-after-each
This is now automatic and shouldn't exist anymore 😅

### PR DESCRIPTION
**Pull request by kentcdodds**
**What**: remove cleanup-after-each file.

**Why**: This is automatic now, so there is no reason to have it

**How**: Remove all the related files and the entry in package.json `files` array.

**Checklist**:

- [ ] Documentation added to the
      [docs site](https://github.com/alexkrolick/testing-library-docs) - Will do this soon
- [x] Tests
- [ ] Typescript definitions updated N/A
- [x] Ready to be merged
      

Closes #432

### CODE REVIEW

**Comment by FredyC** [comment]
I think you went too fast with that, could have been at least deprecated to be removed in next major. It's a relatively small thing but adds unnecessary overhead to upgrading.

**Comment by FredyC** [comment]
Deprecation warning would also teach people about the feature in case someone is not reading release notes too carefully.

**Comment by kentcdodds** [comment]
You're right. I'll add it back with a deprecation warning.

**Comment by kentcdodds** [comment]
Publishing the fix now. I was hasty. Thanks for calling me out.

**Pull request merged**
