### PR TITLE
Add iFood to users

### PR DESCRIPTION
**Pull request by nickmccurdy**
Responding to this request we got in Reactiflux:

> Hi, there! I work at iFood, the largest foodtech delivery in Latin America. I want to understand how do you select the companies that appear in the section Who's Using This in the Testing Library because we would like to join that - our frontend team is a heavy user of your platform! Tks a lot, Larissa

__Note:__ The site appears to only be available in Brazilian Portuguese

### CODE REVIEW

**Comment by kentcdodds** [comment]
I think they wanted to appear on the website.

**Comment by nickmccurdy** [comment]
I got confused because there only seem to be users pages in the repositories, not the site. Should the site have one for all libraries?

**Comment by kentcdodds** [comment]
I'm pretty sure they want to be on this list (on the home page of https://testing-library.com)

image

https://github.com/testing-library/testing-library-docs/blob/6ca45677fcd7c91c5e571b760906a445aaa287ec/website/siteConfig.js

**Comment by nickmccurdy** [comment]
Oh, I didn't notice the wording there, my bad 😓

**Pull request closed without merging**
