### PR TITLE
Drop usage of react-dom/test-utils

### PR DESCRIPTION
**Pull request by eps1lon**
**BREAKING CHANGE**
The `legacyRoot` option is no longer supported now that `ReactDOM.render` has been removed from React. There is no alternative.

To ensure compatibility with React Testing Library 15, make sure you're not using the `legacyRoot` option in any of your calls to `render` from React Testing Library. 

React 18 is still supported but you will see deprecation warnings from `react-dom/test-utils`. Either suppress these warnings or switch to React 19.

### CODE REVIEW

**Comment by MatanBobi** [comment]
Thanks Sebastian. Is there any documentation about this change? Are they just deprecating the module?

**Comment by cayter** [comment]
> Thanks Sebastian. Is there any documentation about this change? Are they just deprecating the module?

This is the related [doc](https://react.dev/warnings/react-dom-test-utils).

**Comment by MatanBobi** [comment]
> > Thanks Sebastian. Is there any documentation about this change? Are they just deprecating the module?
> 
> This is the related [doc](https://react.dev/warnings/react-dom-test-utils).

Thanks.. This was created by @eps1lon himself :)

https://github.com/reactjs/react.dev/blob/main/src/content/warnings/react-dom-test-utils.md

**Comment by eps1lon** [comment]
Favoring https://github.com/testing-library/react-testing-library/pull/1294 which adds React 19 support in a SemVer MINOR.

**Pull request closed without merging**
