### PR TITLE
fix: Remove optional chaining syntax to fix esm

### PR DESCRIPTION
**Pull request by jacobhaile**
**What**: Removing the optional chainging "?" syntax from the index file

**Why**: The optional chaining syntax can cause compilation breaks

**How**: Break out the optional changing into an `&&` statement

**Checklist**:

- [N/A] Documentation added to the
      [docs site](https://github.com/testing-library/testing-library-docs)
- [N/A] Tests
- [N/A] TypeScript definitions updated
- [x] Ready to be merged

### CODE REVIEW

**Comment by MatanBobi** [comment]
Hi @jacobhaile!
Thanks for taking the time to open this.
Since we're targeting Node 14 as the minimal engine and optional chaining is available from Node 14, I believe this change is not needed.
Thanks again!

**Comment by jacobhaile** [comment]
Thanks for the time @MatanBobi!

Does this account for esm files? I upgraded react-testing-library to v14 and I'm seeing my cypress runs impacted because of that optional chaining syntax. I'm on node v16.

**Comment by MatanBobi** [comment]
That's a good question @jacobhaile, I must admit I'm not entirely on the ESM train. I'll have to look into it a bit more. Not sure I'll have the time for it soon so I'm opening this PR and if someone has an opinion, they're more than free to post it :)

**Comment by nickmccurdy** [comment]
> Since we're targeting Node 14 as the minimal engine and optional chaining is available from Node 14, I believe this change is not needed.

@MatanBobi I believe this is correct.

@jacobhaile I can't reproduce this issue with Cypress. Can you please share a reproduction?

**Comment by jacobhaile** [comment]
I can close out -- I no longer get the error after updating to Cypress v13

**Comment by MatanBobi** [comment]
Thanks for the update @jacobhaile :)

**Pull request closed without merging**
